apiVersion: v1
data:
  password: <b64 string> 
  username: <b64 string> 
kind: Secret
metadata:
  name: gitlab-app-user
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  password: <b64 string> 
  username: <b64 string>
kind: Secret
metadata:
  name: gitlab-superuser
type: kubernetes.io/basic-auth
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: ceph-rgw-creds
#data:
#  ACCESS_KEY_ID: <b64 string>
#  ACCESS_SECRET_KEY: <b64 string>
#---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-db-cluster 
spec:
  description: "Example of cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0-system-trixie
  # imagePullSecret is only required if the images are located in a private registry
  # imagePullSecrets:
  #   - name: private_registry_access
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: gitlab-app-user
    # Alternative bootstrap method: start from a backup
    #recovery:
    #  backup:
    #    name: backup-example

  enableSuperuserAccess: true
  superuserSecret:
    name: gitlab-superuser

  storage:
    storageClass: csi-cephfs-sc
    size: 15Gi

#  backup:
#    barmanObjectStore:
#      destinationPath: s3://cluster-example-full-backup/ <--- CEPH RGW
#      endpointURL: http://custom-endpoint:1234
#      s3Credentials:
#        accessKeyId:
#          name: ceph-rgw-creds
#          key: ACCESS_KEY_ID
#        secretAccessKey:
#          name: ceph-rgw-creds
#          key: ACCESS_SECRET_KEY
#      wal:
#        compression: gzip
#        encryption: AES256
#      data:
#        compression: gzip
#        encryption: AES256
#        immediateCheckpoint: false
#        jobs: 2
#    retentionPolicy: "30d"

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: az
