apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: mkdocs-homelab-rpi
  namespace: mkdocs
spec:
  ingressClassName: nginx
  rules:
  - host: homelab-rpi.hyrsh.io
    http:
      paths:
      - backend:
          service:
            name: mkdocs-homelab-rpi-svc
            port:
              number: 8000
        path: /
        pathType: Prefix
