apiVersion: batch/v1
kind: Job
metadata:
  name: updater-cs2
  namespace: mkdocs
spec:
  template:
    metadata:
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
      - image: harbor.hyrsh.io/own-images/git-cloner:v1.2-arm64
        env:
          - name: REPOSITORY_NAME
            value: "cs2-mkdocs"
          - name: REPOSITORY_USER
            value: "hyrsh"
          - name: TOKEN_FILE
            value: "/sec/token/key"
          - name: SUBPATH
            value: "documents"
        name: cloner
        securityContext:
          runAsNonRoot: true
          runAsUser: 2000
          runAsGroup: 2000
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - name: data
            mountPath: /data
          - name: secret
            mountPath: /sec/token
      securityContext:
        fsGroup: 2000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mkdocs-cs2-data
        - name: secret
          secret:
            secretName: mkdocs-cs2
      restartPolicy: Never
