- hosts: all
  become: yes
  become_method: sudo
  remote_user: ansible-admin
  vars:
    ansible_ssh_private_key_file: /datadisk/05_credentials/ssh-keys/admin.private
  vars_files:
    - "vault/av_homelab"
  roles:
    - admin_clean_rpi
