- hosts: hl_lb
  gather_facts: False
  become: True
  become_method: sudo
  remote_user: ansible
  vars_files:
    - "vault/av_homelab"
  roles:
    - expose_ssh_keys
    - setup_node_exporter_raw
  handlers:
  - name: h-clean-exposed-keys
    delegate_to: localhost
    file:
      name: /tmp/ansible_exposed_keys
      state: absent
  - name: "h-restart-node-exporter"
    service:
      name: node-exporter
      state: restarted
      enabled: yes
