site_name: 'Homelab RPI'
#accent colors
#amber,blue,cyan,deep-orange,deep-purple,green,indigo,light-blue,light-green,lime,orange,pink,purple,red,teal,yellow
#primary colors
#amber,black,blue,blue-grey,brown,cyan,deep-orange,deep-purple,green,grey,indigo,light-blue,light-green,lime,orange,pink,purple,red,teal,white,yellow
theme:
  name: 'material'
  logo: 00_assets/rpi_logo_64.png
  favicon: images/rpi_logo_32.png
  palette:
    - scheme: slate
      primary: black
      accent: lime
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to another dark mode
    - scheme: slate
      primary: blue
      accent: amber
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
nav:
  - General: index.md
  - Design: 01_design/lp_design.md
  - Ansible: 08_ansible/lp_ansible.md
  - Raspberry Pi: 02_raspberry/lp_raspberry.md
  - HAProxy & VPN: 07_hprx_vpn/lp_hprx_vpn.md
  - Ceph:
      - Overview: 04_ceph/01_overview.md
      - Setup: 04_ceph/02_setup.md
      - Configuration: 04_ceph/03_config.md
      - Upgrade: 04_ceph/04_upgrade.md
  - Kubernetes:
      - Containers: 03_kubernetes/01_containers.md
      - Overview: 03_kubernetes/00_overview.md
      - Design: 03_kubernetes/03_design.md
      - Setup: 03_kubernetes/02_setup.md
      - Apps:
          - Harbor: 09_apps/lp_harbor.md
          - Grafana: 09_apps/lp_grafana.md
          - Prometheus: 09_apps/lp_prometheus.md
          - MKDocs: 09_apps/lp_mkdocs.md
          - CNPG: 09_apps/lp_cnpg.md
          - Portainer (WebUI): 09_apps/lp_portainer.md
          - Jellyfin: 09_apps/lp_jellyfin.md
  - Material: 05_material/lp_material.md
  - TheBox: 06_thebox/lp_thebox.md
  - Outages: 10_outages/lp_outages.md

